"""
TalentFabric AI — Microsoft Agent Framework implementation.

This is a *real*, runnable implementation against the installed
`agent_framework` package (agent-framework-core 1.8.1), wired to the same
grounded agent logic in src/agents/* and the same three local IQ layers
(src/iq_layers/*). It satisfies the challenge requirement to:

    "Use Microsoft Foundry (UI or SDK) and/or the Microsoft Agent
     Framework ... Demonstrate reasoning and multi-step decision-making
     across agents."

Two graphs are built, mirroring the two architecture diagrams:

1. `build_learner_subworkflow(...)` -- the "Sequential Student Readiness
   Subworkflow" (diagram 1's inner box):

       learning_path_curator -> study_plan_generator -> engagement_agent
           -> assessment_agent
                 |--(loop_back == True)--> back to study_plan_generator
                 |--(loop_back == False)--> workflow output

   This is a genuine Agent Framework `Workflow` with a conditional
   back-edge implementing the Critic/Verifier loop (capped by
   `assessment_agent.MAX_ITERATIONS`).

2. `build_team_workflow(...)` -- "Input -> [fan-out: 4 parallel Sequential
   Student Readiness Subworkflows] -> Assess & Aggregate" (diagram 1's
   outer shape):

       team_dispatcher --(fan-out)--> learner_runner_0..3
                                            |
                                       (each runs its own nested
                                        per-learner subworkflow)
                                            |
       learner_runner_0..3 --(fan-in)--> manager_insights_agent

   Every synthetic team has exactly 4 learners, so a static fan-out of 4
   runner executors maps 1:1 onto the roster.

LLM narration uses `get_chat_client()` from src/agents/base.py: if
AZURE_OPENAI_* env vars are set, narration is generated by your Azure
OpenAI / Microsoft Foundry deployment; otherwise the templated offline
fallback is used. Either way, the *graph structure and grounded reasoning*
(retrieval, readiness scoring, scheduling, loop-back, aggregation) are
identical -- only the natural-language narration changes.

Run:
    python -m src.agent_framework_workflow
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from agent_framework import Executor, WorkflowContext, WorkflowBuilder, handler

from src.agents import (
    assessment_agent,
    engagement_agent,
    learning_path_curator,
    manager_insights_agent,
    study_plan_generator,
)
from src.agents.base import ChatClient, get_chat_client
from src.iq_layers.fabric_iq import FabricIQ
from src.iq_layers.foundry_iq import FoundryIQ
from src.iq_layers.work_iq import WorkIQ

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

LEARNERS_PER_TEAM = 4  # fixed in the synthetic roster


# ---------------------------------------------------------------------------
# Per-learner subworkflow executors
# ---------------------------------------------------------------------------
class CuratorExecutor(Executor):
    """Learning Path Curator -> Foundry IQ"""

    def __init__(self, id: str, foundry_iq: FoundryIQ, fabric_iq: FabricIQ, chat_client: ChatClient):
        super().__init__(id=id)
        self.foundry_iq = foundry_iq
        self.fabric_iq = fabric_iq
        self.chat_client = chat_client

    @handler
    async def run(self, state: dict, ctx: WorkflowContext[dict]) -> None:
        result = learning_path_curator.run(
            state["learner_id"], self.foundry_iq, self.fabric_iq, self.chat_client
        )
        state = dict(state)
        state["curator"] = result
        state["trace"] = state.get("trace", []) + [result]
        await ctx.send_message(state)


class PlannerExecutor(Executor):
    """Study Plan Generator -> Fabric IQ (Planner-Executor)"""

    def __init__(self, id: str, fabric_iq: FabricIQ, chat_client: ChatClient, foundry_iq: FoundryIQ):
        super().__init__(id=id)
        self.fabric_iq = fabric_iq
        self.chat_client = chat_client
        self.foundry_iq = foundry_iq

    @handler
    async def run(self, state: dict, ctx: WorkflowContext[dict]) -> None:
        result = study_plan_generator.run(
            state["learner_id"],
            self.fabric_iq,
            self.chat_client,
            target_hours_override=state.get("next_hours_target"),
            iteration=state.get("iteration", 1),
            foundry_iq=self.foundry_iq,
        )
        state = dict(state)
        state["plan"] = result
        state["trace"] = state["trace"] + [result]
        await ctx.send_message(state)


class EngagementExecutor(Executor):
    """Engagement Agent -> Work IQ"""

    def __init__(self, id: str, fabric_iq: FabricIQ, work_iq: WorkIQ, chat_client: ChatClient):
        super().__init__(id=id)
        self.fabric_iq = fabric_iq
        self.work_iq = work_iq
        self.chat_client = chat_client

    @handler
    async def run(self, state: dict, ctx: WorkflowContext[dict]) -> None:
        learner = self.fabric_iq.get_learner(state["learner_id"])
        result = engagement_agent.run(
            learner["employee_id"], state["plan"]["plan"], learner, self.work_iq, self.chat_client
        )
        state = dict(state)
        state["engagement"] = result
        state["trace"] = state["trace"] + [result]
        await ctx.send_message(state)


class AssessmentExecutor(Executor):
    """Assessment Agent -> Foundry IQ (cited questions) + Fabric IQ (thresholds); Critic/Verifier"""

    def __init__(self, id: str, fabric_iq: FabricIQ, chat_client: ChatClient, foundry_iq: FoundryIQ):
        super().__init__(id=id)
        self.fabric_iq = fabric_iq
        self.chat_client = chat_client
        self.foundry_iq = foundry_iq

    @handler
    async def run(self, state: dict, ctx: WorkflowContext[dict, dict]) -> None:
        result = assessment_agent.run(
            state["learner_id"],
            state["curator"]["resources"],
            state["plan"]["plan"],
            self.fabric_iq,
            self.chat_client,
            iteration=state.get("iteration", 1),
            foundry_iq=self.foundry_iq,
        )
        state = dict(state)
        state["assessment"] = result
        state["trace"] = state["trace"] + [result]
        state["loop_back"] = result["loop_back"]

        if result["loop_back"]:
            # Critic/Verifier loop-back: send a new state back to the
            # Study Plan Generator with an adjusted hours target.
            state["next_hours_target"] = result["next_hours_target"]
            state["iteration"] = state.get("iteration", 1) + 1
            await ctx.send_message(state)
        else:
            await ctx.yield_output(state)


def build_learner_subworkflow(
    foundry_iq: FoundryIQ, work_iq: WorkIQ, fabric_iq: FabricIQ, chat_client: ChatClient
):
    """Build the 'Sequential Student Readiness Subworkflow' graph for one learner."""
    curator = CuratorExecutor("learning_path_curator", foundry_iq, fabric_iq, chat_client)
    planner = PlannerExecutor("study_plan_generator", fabric_iq, chat_client, foundry_iq)
    engagement = EngagementExecutor("engagement_agent", fabric_iq, work_iq, chat_client)
    assessment = AssessmentExecutor("assessment_agent", fabric_iq, chat_client, foundry_iq)

    builder = WorkflowBuilder(start_executor=curator, output_from=[assessment])
    builder.add_edge(curator, planner)
    builder.add_edge(planner, engagement)
    builder.add_edge(engagement, assessment)
    # Critic/Verifier loop-back, capped via assessment_agent.MAX_ITERATIONS
    builder.add_edge(assessment, planner, condition=lambda s: s.get("loop_back") is True)
    return builder.build()


# ---------------------------------------------------------------------------
# Team-level workflow: fan-out per-learner subworkflows -> fan-in to Manager Insights
# ---------------------------------------------------------------------------
class TeamDispatcherExecutor(Executor):
    """Input stage: resolve a team_id to its learner roster."""

    def __init__(self, id: str, fabric_iq: FabricIQ):
        super().__init__(id=id)
        self.fabric_iq = fabric_iq

    @handler
    async def run(self, team_id: str, ctx: WorkflowContext[dict]) -> None:
        learners = self.fabric_iq.list_learners(team_id)
        learner_ids = [l["learner_id"] for l in learners]
        await ctx.send_message({"team_id": team_id, "learner_ids": learner_ids})


class LearnerRunnerExecutor(Executor):
    """Runs one nested 'Sequential Student Readiness Subworkflow' for learner[index]."""

    def __init__(
        self,
        id: str,
        index: int,
        foundry_iq: FoundryIQ,
        work_iq: WorkIQ,
        fabric_iq: FabricIQ,
        chat_client: ChatClient,
    ):
        super().__init__(id=id)
        self.index = index
        self.foundry_iq = foundry_iq
        self.work_iq = work_iq
        self.fabric_iq = fabric_iq
        self.chat_client = chat_client

    @handler
    async def run(self, dispatch: dict, ctx: WorkflowContext[dict]) -> None:
        learner_ids = dispatch["learner_ids"]
        if self.index >= len(learner_ids):
            # Defensive: teams smaller than LEARNERS_PER_TEAM contribute nothing.
            await ctx.send_message(None)
            return

        learner_id = learner_ids[self.index]
        learner = self.fabric_iq.get_learner(learner_id)

        sub_workflow = build_learner_subworkflow(
            self.foundry_iq, self.work_iq, self.fabric_iq, self.chat_client
        )
        events = await sub_workflow.run({"learner_id": learner_id, "iteration": 1, "trace": []})
        final_state = next(ev.data for ev in events if ev.type == "output")

        learner_result = {
            "learner_id": learner_id,
            "employee_id": learner["employee_id"],
            "role": learner["role"],
            "team_id": learner["team_id"],
            "curator": final_state["curator"],
            "plan": final_state["plan"],
            "engagement": final_state["engagement"],
            "assessment": final_state["assessment"],
            "iterations": final_state.get("iteration", 1),
            "trace": final_state["trace"],
        }
        await ctx.send_message(learner_result)


class ManagerInsightsExecutor(Executor):
    """Manager Insights Agent -> Work IQ + Fabric IQ (fan-in / aggregation)"""

    def __init__(self, id: str, fabric_iq: FabricIQ, chat_client: ChatClient, foundry_iq: FoundryIQ):
        super().__init__(id=id)
        self.fabric_iq = fabric_iq
        self.chat_client = chat_client
        self.foundry_iq = foundry_iq

    @handler
    async def run(self, learner_results: list[Any], ctx: WorkflowContext[dict, dict]) -> None:
        results = [r for r in learner_results if r is not None]
        team_id = results[0]["team_id"] if results else "UNKNOWN"
        report = manager_insights_agent.run(
            team_id, results, self.fabric_iq, self.chat_client, foundry_iq=self.foundry_iq
        )
        await ctx.yield_output({"team_id": team_id, "learner_results": results, "manager_insights": report})


def build_team_workflow(foundry_iq: FoundryIQ, work_iq: WorkIQ, fabric_iq: FabricIQ, chat_client: ChatClient):
    """Build the team-level fan-out/fan-in graph ('Assess & Aggregate team readiness results')."""
    dispatcher = TeamDispatcherExecutor("team_dispatcher", fabric_iq)
    runners = [
        LearnerRunnerExecutor(f"learner_runner_{i}", i, foundry_iq, work_iq, fabric_iq, chat_client)
        for i in range(LEARNERS_PER_TEAM)
    ]
    manager = ManagerInsightsExecutor("manager_insights_agent", fabric_iq, chat_client, foundry_iq)

    builder = WorkflowBuilder(start_executor=dispatcher, output_from=[manager])
    builder.add_fan_out_edges(dispatcher, runners)
    builder.add_fan_in_edges(runners, manager)
    return builder.build()


# ---------------------------------------------------------------------------
# Convenience wrapper + CLI
# ---------------------------------------------------------------------------
class AgentFrameworkTalentFabricWorkflow:
    def __init__(self):
        self.foundry_iq = FoundryIQ(DATA_DIR / "knowledge_base")
        self.work_iq = WorkIQ(DATA_DIR / "work_activity_signals.json")
        self.fabric_iq = FabricIQ(
            DATA_DIR / "fabric_iq_semantic_model.json", DATA_DIR / "learners.json"
        )
        self.chat_client = get_chat_client()

    async def run_team(self, team_id: str) -> dict:
        workflow = build_team_workflow(self.foundry_iq, self.work_iq, self.fabric_iq, self.chat_client)
        events = await workflow.run(team_id)
        return next(ev.data for ev in events if ev.type == "output")

    async def run_all_teams(self) -> list[dict]:
        return [await self.run_team(team_id) for team_id in self.fabric_iq.list_teams()]


async def _main():
    wf = AgentFrameworkTalentFabricWorkflow()
    results = await wf.run_all_teams()

    out_path = Path(__file__).resolve().parent.parent / "run_output_agent_framework.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    for team_result in results:
        print(f"\n=== {team_result['team_id']} (Agent Framework) ===")
        print(team_result["manager_insights"]["narrative"])
        for lr in team_result["learner_results"]:
            print(
                f"  - {lr['learner_id']} ({lr['role']}): "
                f"{lr['assessment']['readiness']['readiness_status']} "
                f"(risk={lr['assessment']['readiness']['risk_level']}, "
                f"iterations={lr['iterations']})"
            )

    print(f"\nFull trace written to {out_path}")


if __name__ == "__main__":
    asyncio.run(_main())
